wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1667077990.997109
    t:
      1:
      - 1
      - 37
      - 38
      - 41
      - 55
      - 60
      2:
      - 1
      - 37
      - 38
      - 41
      - 55
      - 60
      3:
      - 13
      - 23
      4: 3.8.13
      5: 0.13.4
      8:
      - 5
