metadata:
  wandb_entity: prj-research
  wandb_project: Learning-Frustum-Proposals
  wandb_group: Debugging
  run_name:
  viz: True
model:
  cfg: "/Users/stephennelson/Projects/Learning-Frustum-Proposals/models/cfgs/learned_frustums.yaml"
  weights: null # path to pretained weights
dataset:
  dir: Kitti # Kitti, SunRGBD, 3DBev24K, Coolers
  use_normals: False
  drop_last: False
  cache: False  # bool or float in [0,1]
  notest: False
  num_workers: 8
  shuffle: True # shuffle points
  sample_points: null
optimization:
  resume: False
  epochs: 5
  learning_rate: 0.001
  optimizer: adam
  batch_size: 4
  test_batch_size: 4
  dropout: 0.0
  cuda: False
  weight_decay: 0.1

data_augmentation:
  mirror_x:
    apply: True
    probability: 0.2
  add_noise:
    apply: True
    samples: 0.1
    mean: 0
    std: 0.02
  resize:
    apply: True
    samples: 0.2
    mean: 0
    std: 0.05
